import { analysisInputSchema } from "./schemas";
import type { AnalysisInput, AnalysisResult, ImportCosts, Scenario, ScoreBreakdown, ScoreWeights } from "./types";
export type { AnalysisInput, AnalysisResult, ImportCosts, Scenario, ScoreBreakdown, ScoreWeights } from "./types";
export function calculateTotalCost(purchasePrice:number,costs:ImportCosts){return purchasePrice+Object.values(costs).reduce((total,cost)=>total+cost,0)}
export function calculateProfit(salePrice:number,totalCost:number){return salePrice-totalCost}
export function calculateCapitalCost(totalCost:number,annualRate:number,holdingDays:number){return totalCost*(annualRate/100)*(holdingDays/365)}
export function calculateROI(adjustedProfit:number,totalCost:number){return totalCost===0?0:(adjustedProfit/totalCost)*100}
export function calculateMargin(adjustedProfit:number,salePrice:number){return salePrice===0?0:(adjustedProfit/salePrice)*100}
export function calculateBreakEven(totalCost:number,capitalCost:number){return totalCost+capitalCost}
export function calculateMaxBuyPrice(input:Pick<AnalysisInput,"expectedSalePrice"|"costs"|"holdingDays"|"annualCapitalCostRate"|"targetRoi">){const fixedCosts=Object.values(input.costs).reduce((total,cost)=>total+cost,0);const capitalFactor=(input.annualCapitalCostRate/100)*(input.holdingDays/365);return Math.max(0,input.expectedSalePrice/(1+capitalFactor+input.targetRoi/100)-fixedCosts)}
export function calculateScenarios(input:AnalysisInput):Scenario[]{return [{name:"Conservador" as const,salePrice:input.expectedSalePrice*.94},{name:"Normal" as const,salePrice:input.expectedSalePrice},{name:"Optimista" as const,salePrice:input.expectedSalePrice*1.06}].map(item=>{const totalCost=calculateTotalCost(input.purchasePrice,input.costs);const capitalCost=calculateCapitalCost(totalCost,input.annualCapitalCostRate,input.holdingDays);const adjustedProfit=calculateProfit(item.salePrice,totalCost)-capitalCost;return {...item,adjustedProfit,roi:calculateROI(adjustedProfit,totalCost)}})}
const balancedWeights:ScoreWeights={roi:30,saleSpeed:20,absoluteProfit:15,risk:15,marketPrice:10,capitalRequired:10};
export function calculateScore({roi,holdingDays,adjustedProfit,marketDiscount=0,capitalRequired=0,weights=balancedWeights}:{roi:number;holdingDays:number;adjustedProfit:number;marketDiscount?:number;capitalRequired?:number;weights?:ScoreWeights}):ScoreBreakdown{const clamp=(value:number,maximum:number)=>Math.max(0,Math.min(maximum,value));const breakdown={roi:clamp(roi/25*weights.roi,weights.roi),saleSpeed:clamp((90-holdingDays)/90*weights.saleSpeed,weights.saleSpeed),absoluteProfit:clamp(adjustedProfit/5000*weights.absoluteProfit,weights.absoluteProfit),risk:clamp(weights.risk-(holdingDays>90?weights.risk*.55:holdingDays/90*weights.risk*.27),weights.risk),marketPrice:clamp(marketDiscount/15*weights.marketPrice,weights.marketPrice),capitalRequired:clamp(weights.capitalRequired-capitalRequired/50000*weights.capitalRequired,weights.capitalRequired)};return {...breakdown,total:Object.values(breakdown).reduce((total,value)=>total+value,0)}}
export function analyzeVehicle(rawInput:AnalysisInput):AnalysisResult{const input=analysisInputSchema.parse(rawInput);const totalCost=calculateTotalCost(input.purchasePrice,input.costs);const grossProfit=calculateProfit(input.expectedSalePrice,totalCost);const capitalCost=calculateCapitalCost(totalCost,input.annualCapitalCostRate,input.holdingDays);const adjustedProfit=grossProfit-capitalCost;const roi=calculateROI(adjustedProfit,totalCost);return {totalCost,grossProfit,capitalCost,adjustedProfit,roi,margin:calculateMargin(adjustedProfit,input.expectedSalePrice),profitPerDay:adjustedProfit/input.holdingDays,breakEven:calculateBreakEven(totalCost,capitalCost),maxBuyPrice:calculateMaxBuyPrice(input),scenarios:calculateScenarios(input),score:calculateScore({roi,holdingDays:input.holdingDays,adjustedProfit,capitalRequired:totalCost,weights:input.scoreWeights})}}
