import { analysisInputSchema } from "./schemas";
import type { AnalysisInput, AnalysisResult, ImportCosts, Scenario, ScoreBreakdown } from "./types";
export type { AnalysisInput, AnalysisResult, ImportCosts, Scenario, ScoreBreakdown } from "./types";
export function calculateTotalCost(purchasePrice:number,costs:ImportCosts){return purchasePrice+Object.values(costs).reduce((total,cost)=>total+cost,0)}
export function calculateProfit(salePrice:number,totalCost:number){return salePrice-totalCost}
export function calculateCapitalCost(totalCost:number,annualRate:number,holdingDays:number){return totalCost*(annualRate/100)*(holdingDays/365)}
export function calculateROI(adjustedProfit:number,totalCost:number){return totalCost===0?0:(adjustedProfit/totalCost)*100}
export function calculateMargin(adjustedProfit:number,salePrice:number){return salePrice===0?0:(adjustedProfit/salePrice)*100}
export function calculateBreakEven(totalCost:number,capitalCost:number){return totalCost+capitalCost}
export function calculateMaxBuyPrice(input:Pick<AnalysisInput,"expectedSalePrice"|"costs"|"holdingDays"|"annualCapitalCostRate"|"targetRoi">){const fixedCosts=Object.values(input.costs).reduce((total,cost)=>total+cost,0);const capitalFactor=(input.annualCapitalCostRate/100)*(input.holdingDays/365);return Math.max(0,input.expectedSalePrice/(1+capitalFactor+input.targetRoi/100)-fixedCosts)}
export function calculateScenarios(input:AnalysisInput):Scenario[]{return [{name:"Conservador" as const,salePrice:input.expectedSalePrice*.94},{name:"Normal" as const,salePrice:input.expectedSalePrice},{name:"Optimista" as const,salePrice:input.expectedSalePrice*1.06}].map(item=>{const totalCost=calculateTotalCost(input.purchasePrice,input.costs);const capitalCost=calculateCapitalCost(totalCost,input.annualCapitalCostRate,input.holdingDays);const adjustedProfit=calculateProfit(item.salePrice,totalCost)-capitalCost;return {...item,adjustedProfit,roi:calculateROI(adjustedProfit,totalCost)}})}
export function calculateScore({roi,holdingDays,adjustedProfit,marketDiscount=0,capitalRequired=0}:{roi:number;holdingDays:number;adjustedProfit:number;marketDiscount?:number;capitalRequired?:number}):ScoreBreakdown{const clamp=(value:number)=>Math.max(0,Math.min(100,value));const breakdown={roi:clamp(roi/25*30),saleSpeed:clamp((90-holdingDays)/90*20),absoluteProfit:clamp(adjustedProfit/5000*15),risk:clamp(15-(holdingDays>90?8:holdingDays/90*4)),marketPrice:clamp(marketDiscount/15*10),capitalRequired:clamp(10-capitalRequired/50000*10)};return {...breakdown,total:Object.values(breakdown).reduce((total,value)=>total+value,0)}}
export function analyzeVehicle(rawInput:AnalysisInput):AnalysisResult{const input=analysisInputSchema.parse(rawInput);const totalCost=calculateTotalCost(input.purchasePrice,input.costs);const grossProfit=calculateProfit(input.expectedSalePrice,totalCost);const capitalCost=calculateCapitalCost(totalCost,input.annualCapitalCostRate,input.holdingDays);const adjustedProfit=grossProfit-capitalCost;return {totalCost,grossProfit,capitalCost,adjustedProfit,roi:calculateROI(adjustedProfit,totalCost),margin:calculateMargin(adjustedProfit,input.expectedSalePrice),profitPerDay:adjustedProfit/input.holdingDays,breakEven:calculateBreakEven(totalCost,capitalCost),maxBuyPrice:calculateMaxBuyPrice(input),scenarios:calculateScenarios(input)}}
